cdklabs/cdk-from-cfn

- src/ir/conditions.rs
- src/ir/mod.rs
- src/lib.rs
- src/main.rs
- src/parser/condition.rs
Intermediate Representation is needed to resolve a lot of odd
constraints that don't really belong in the parse phase. Examples:
* IR should figure out the correct names for cdk vs not cdk
* IR should figure out ordering issues, if they arise
Post-IR phases should take IR and expect essentially "just instructions"
to be plopped out from the IR in the language of choice. You should be
able to analyze IR and always know what will be emitted, which is also
helpful for tests.
Conditions is the first move to IR, though a lot of it is just duplicate
traversal of the parse tree, which is unfortunate.
> Start building IR

- src/ir/mod.rs
- src/ir/reference.rs
- src/ir/resources.rs
- src/lib.rs
- src/main.rs
- src/parser/parameters.rs
- src/parser/resource.rs
- src/specification/mod.rs
- src/synthesizer/typescript_synthesizer.rs
Resources in intermediate representation was the last holdover
to a working program without manual manipulation of typescript.
This change adds "Complexity", a concept to help translate CDK
interfaces appropriately for L1s, and adds this decoration to
ResourceIr. This change also adds a few other bells and whistles
along the way while debugging final output (like AWS::AccountId)
> Translate ResourceValue to ResourceIr to add metadata

- src/ir/resources.rs
Strings are a-plenty in CloudFormation. This change will make it so
if you have a string but your type is a bool or integer, then it will
force-cast on your behalf like CloudFormation does.
> Add String force casting

- README.md
- src/ir/importer.rs
- src/main.rs
- src/parser/lookup_table.rs
- src/synthesizer/typescript_synthesizer.rs
[Previous PR](https://github.com/iph/noctilucent/pull/49) cannot be updated for some reason. So I am creating a new one. 
**Can you help squash the commits on the UI before merging?**
> Add option to write output to a file and fix minor TypeScript coding style & formatting issues.

- src/parser/resource.rs
- tests/tests.rs
Turns out the shorthand in the docs here:
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/intrinsic-function-reference-getatt.html
Is valid in json as well. This commit will add that support for
anyone who stumbled upon that gem.
> fix: Add parser support for shorthand Fn::GetAtt

- src/synthesizer/typescript_synthesizer.rs
Handling Custom::<CustomName> when synthesizing custom resources. Originally thought about converting all `Custom::` resource types to `AWS::CloudFormation::CustomResource` in resources/translates_resources(), but given immutability turned out to be a more involved option. 
Output:
```
const resourceType = new cloudformation.CfnCustomResource(this, 'Name', {
serviceToken: FunctionName.attrArn
});
```
> Handling Custom::<CustomName> when synthesizing custom resources

- Cargo.toml
- src/ir/resources.rs
- src/parser/resource.rs
- src/synthesizer/typescript_synthesizer.rs
- tests/tests.rs
**What is the problem?**
As is noctilucent is unable to convert a CFN template if there exists floats in the template. I ran into this on the Threshold property for a CloudWatch alarm, but looking at the specification, there are a couple different resources that could run into this (any property that allows a Double)
**What is the solution?**
While parsing, we will check if a string is an integer or not, using https://docs.rs/numberkit/latest/numberkit/fn.is_digit.html. If it is we will continue with today's parsing, otherwise we will use a new ResourceValue::Double. The not straightforward thing that I had to do was create essentially a wrapper around the f64 type as it does not implement Eq. 
**Example error**
when trying to convert the following resource:
```
"AlarmResource": { …
```
> Add capability to parse and convert floats in CFN templates

- src/ir/mod.rs
- src/ir/resources.rs
- src/ir/sub.rs
- src/parser/mod.rs
There was a recent bug filed around substitution not working for a "no substitution" corner case. The parse would not handle such a case because it could not consume the rest of the output UNLESS it had a $ in it.
As such, rewrote the parser a bit to consume the rest of the tokens and return eof on the next go round instead. Also move Sub to IR. Though it is technically a parser, the tokenization of the output doesn't occur until IR output, so it belongs there more. It may make sense to revisit if we want that level of tokenization in an earlier phase in the future, but for now this seems fine.
Fixes #66
> Fix no substitution bug

- src/ir/mappings.rs
- src/ir/resources.rs
- src/lib.rs
- src/parser/lookup_table.rs
- src/parser/resource.rs
- src/primitives/mod.rs
- src/synthesizer/typescript_synthesizer.rs
- tests/tests.rs
It turns out that cloudformation actually allows arbitrary types in Fn::Mappings. Within that, it's also not uniform types as well.
This update handles the arbitrary types for non-array-based inputs and will "opt out" for non-array-based complex structures with an `any` mode, leaving it up to the user to resolve that problem in typescript. Also, in order to reuse f64 types, moved WrapperF64 to a primitives folder that spans the gap of parser and ir.
> Update lookup table to handle arbitrary types

- src/ir/resources.rs
When passing down types into an Fn::Mapping, I originally expected to continue passing down the types into deeply nested structures.
This actually doesn't make sense. As an example, let's take a look at ReadCapacityUnits in DDB:
```
"ReadCapacityUnits" : 3000
```
Simple. It requires an integer.
When reading this fun mutated version:
```
"ReadCapacityUnits": {"Fn::FindInMap": ["DDBValue", "Table"] }
```
or something or other. ReadCapacityUnits is indeed still requiring an integer, but FindInMap is not, it is requiring two input strings in an array. The original code would pass the complexity type from the parent (in this case RSU), but that is incorrect and so would not work for resolving anything other than strings in maps. In this newest iteration, Mappings will now only resolve strings. …
> Upgrade type structure for Fn::FindInMappings

- src/specification/mod.rs
The specification for CloudFormation sucks. It doesn't follow it's own standards and creates invalid JSON. This change fixes some of those rough edges by deduping in a hashmap and "hoping for the best".
Also change required type to be optional since some teams can't publish correctly on that as well.
> Fix deduping problems in specification file

- Cargo.toml
- README.md
- src/main.rs
Add an additional option to specify the file format of the CFN template in order to support yaml CFN templates.
> Add yaml support for CFN templates

- src/ir/outputs.rs
- src/parser/output.rs
- src/synthesizer/typescript_synthesizer.rs
- Added descriptions and condition handling for outputs. Now if an output has a condition, it will wrap the output in an if statement
```
"Output1":
"Condition": "Condition1"
"Description": "A CFN output"
"Export":
"Name":
"Fn::Sub": "${AWS::StackName}-Output"
"Value":
"Ref": "SomeResource"
```
becomes
```
if (condition1) {
new cdk.CfnOutput(this, 'Output1', {
exportName: `${this.stackName}-Output`,
description: 'A CFN output',
value: someResource.ref
});
}
```
- Modified resources so if the resource requires an if statement, the check for undefined occurs within the if statement. This fixes an issue where a resource is only set when a specific condition is true and is only reference in a resource when that condition is true, but the undefined check was happening outside the if statement, …
> Add output conditions and fixed resource reference

- src/synthesizer/typescript_synthesizer.rs
- Using {} in the if statement does not compile and needs to be undefined.
- CDK build will fail when using [] on Fn.GetAzs as it's a token and requires Fn.Select when selecting on it.
> Fixed using {} instead of undefined and to use Fn.select on Fn.getAZs

- src/ir/resources.rs
- src/ir/sub.rs
- src/lib.rs
- src/synthesizer/typescript_synthesizer.rs
So, when the Sub parser goes through, you can get a blob like:
```
"Fn::Sub": "echo ${lol}"
```
which would transform lol into a variable, as it's surrounded by ${}. It turns out that CFN doesn't need a reference of any kind, and will just output the string inside if it doesn't match any origin. Meanwhile, my system would attempt to topological sort `lol` off a Logical Id, but not find a Logical Id! So it would crash.
There were a few other bugs in this patch (escaping ticks, simplify the parser) that aren't worth mentioning.
> (fix): Sub variables only saw References

- src/main.rs
- src/synthesizer/mod.rs
- src/synthesizer/typescript_synthesizer.rs
Initial work to generalize the contract of synthesizers to prepare for addition of more target languages. The current API is very bare bones, and may be modified/expanded in the future.
> chore: introduce the `Synthesizer` trait

- Cargo.toml
- src/lib.rs
- src/main.rs
- src/parser/condition.rs
- src/parser/lookup_table.rs
- src/parser/output.rs
- src/parser/parameters.rs
- src/parser/resource.rs
- src/specification/mod.rs
- tests/json.rs
- tests/tests.rs
Since all valid JSON is also valid YAML, the `serde_yaml` library can be used to parse all kinds of input, without requiring user selection. Also changes the initial internal representation to be a YAML value instead of a JSON value, which is a little more expressive (although it's not clear whether this is a good thing in this particular case; but at least it reduces the dependency surface).
> chore: remove dependency on `serde_json`

- src/parser/lookup_table.rs
- src/parser/output.rs
- src/parser/parameters.rs
- tests/tests.rs
Make sure rust knows how to compare hashmaps and make the template test, test on all aspects of the template
> chore: make noctilucent more testable

- tasks/coverage.sh
- tests/tests.rs
You can run `./tasks/coverage.sh` and the coverage reports are produced under:
- HTML: `target/coverage/html`
- LCov: `target/coverage/lcov.info`
The `lcov` report is automatically picked up by VSCode's [Coverage Gutters](https://marketplace.visualstudio.com/items?itemName=ryanluker.vscode-coverage-gutters) extension so developers can see coverage information in-line with the editor.
> chore: add coverage gathering script

- src/ir/resources.rs
- src/parser/resource.rs
- src/synthesizer/typescript_synthesizer.rs
Added unit tests for parsing of all intrinsic functions as `ResourceValue` objects and added missing support for the `Fn::Split` instrinsic function.
Note that the `Fn::Transform` function is still unsupported, and neither are the `Fn::Length` and `Fn::ToJsonString` functions which require the `AWS::LanguageExtensions` transform to be used.
> feat: add support for `Fn::Split`

- .github/workflows/pr-actions.yml
Split out running tests and lint/format checks for cleaner understanding just looking at the review. Also update tests to run code coverage task.
> chore: Split out actions, use code coverage test

- Cargo.toml
- src/ir/resources.rs
- src/parser/condition.rs
- src/parser/intrinsics.rs
- src/parser/mod.rs
- src/parser/output.rs
- src/parser/resource.rs
- src/primitives/mod.rs
- tests/tests.rs
Parse directly into the `*ParseTree` structures instead of going through `serde_yaml::Value` as an initial step. This replaces a bunch of `Derive` implementations of `serde::Deserialize` with hand-coded ones, and completely removes the `build_resource_recursively` function (in favor of directly parsing).
This is not the complete implementation of the refactor (it'd be too big), and instead of an initial pass that focuses specifically on the `ResourceValue` `enum`. It also refactored intrinsics into an `IntrinsicFunction` `enum` to make the semantics a little easier to track here, and also to consolidate the parsing logic in a separate location.
> chore: remove steps to parse CloudFormation templates

- src/parser/intrinsics.rs
- tests/tests.rs
needed intrinsics to be able to understand the fn::if function to unblock this test. Thanks @RomainMuller for catching that
> fix: add test for fn::and as well as fix intrinsics

- .github/codecov.yml
- .github/workflows/pr-actions.yml
- Cargo.toml
- src/errors/mod.rs
- src/ir/conditions.rs
- src/ir/mod.rs
- src/ir/reference.rs
- src/ir/resources.rs
- tasks/coverage.sh
- tests/end-to-end/simple/app.ts
Allows emitting optional-chained references when the origin is conditional, so as to avoid the TypeScript compiler complaining about possibly null dereference.
> feat: track reference origin nullability

- tests/tests.rs
Just simply renaming test variables to make things more explicit than just 'a'
> chore: test variable naming consistency

- src/errors/mod.rs
- src/primitives/mod.rs
Based on `noctilucent/target/coverage/html/src/primitives/mod.rs.html`
> chore: tests for skipped lines

- .github/workflows/schema.yml
Pull Requests for schema changes are no longer working. They started to break because in v1.5+, dist files were no longer included in the action -- so things are just busted. 
The recommendation both on the marketplace and the issue is to just use the recommended version (either v1.x or v1). We don't need advanced functionality, so tagging us to v1.
> chore: Fix PR Action

- src/ir/conditions/mod.rs
- src/parser/condition/mod.rs
- src/parser/condition/tests.rs
- src/synthesizer/golang/mod.rs
- src/synthesizer/typescript/mod.rs
- tests/end-to-end/simple/app.go
- tests/end-to-end/simple/app.ts
- tests/end-to-end/simple/template.yml
Turns out you can use split (and probably join) in conditions. This adds the functionality for split to be used, which unblocks a few templates found that require that.
> feat: allow split/select to be used in conditions

- src/ir/conditions/mod.rs
- src/parser/condition/mod.rs
- src/parser/condition/tests.rs
- src/synthesizer/golang/mod.rs
- src/synthesizer/typescript/mod.rs
- tests/end-to-end/simple/app.go
- tests/end-to-end/simple/app.ts
- tests/end-to-end/simple/template.yml
Apparently conditions can just be "another condition". Weird use case, but I've found some templates that have this. Added Condition as the highest level to allow those templates to work.
> feat: Allow Conditions to be used in isolation

- src/ir/conditions/mod.rs
- src/parser/condition/mod.rs
- src/synthesizer/golang/mod.rs
- tests/end-to-end/simple/app.go
- tests/end-to-end/simple/app.ts
- tests/end-to-end/simple/template.yml
Go does not have a ternary operator and if-else statements are not expressions, so one needs to compose an IIFE in order to emulate the semantics of the elvis operator (`?:`).
This can be pretty wordy, and requires being able to determine the appropriate value type locally, which is cumbersome. Fortunately, go generics can be used to let the Go compiler infer the correct type to use, and this in turns reduces the verbosity of the construct.
This introduces an `ifCondition` generic function to implement the ternary expression in a generic manner, which solves that problem.
> fix(go): use generics trick to implement `Fn::If`

- src/parser/condition/mod.rs
- src/parser/resource/mod.rs
- tests/end-to-end/simple/template.yml
With the move to proper typing in parsing, we accidentally shed some valuable transforms that CloudFormation takes on behalf of the customer. This brings back those transforms.
Specifically:
- DependsOn is allowed to have a single value
- Select index can be a string that is parse-able into an int
> fix(all): properly transform depends_on, and selection

- src/lib.rs
- src/main.rs
- src/synthesizer/golang/mod.rs
- src/synthesizer/java/mod.rs
- src/synthesizer/mod.rs
- src/synthesizer/typescript/mod.rs
- tests/end-to-end.rs
- tests/end-to-end/simple/App.java
- tests/end-to-end/simple/app.go
- tests/end-to-end/simple/app.ts
- tests/end-to-end/vpc/App.java
- tests/end-to-end/vpc/app.go
- tests/end-to-end/vpc/app.ts
This change adds a CLI input `--stack-name` that users can specify. The default value of `NoctStack` is unchanged if no input is provided by the user.
> feat: enable users to define stack name

- src/synthesizer/java/mod.rs
- src/synthesizer/typescript/mod.rs
- tests/end-to-end/simple/App.java
- tests/end-to-end/simple/app.go
- tests/end-to-end/simple/app.ts
- tests/end-to-end/simple/template.yml
- tests/end-to-end/vpc/App.java
Support non primitive parameters for TypeScript and Java. (e.g `AWS::EC2::VPC::Id`, `AWS::SSM::Parameter::Value<String>`)
Currently, noctilucent looks like support only String type parameter. For example, we can't restore a project even if it's just initialized with CDK.
The steps to reproduce are as follows
1. npx cdk init app --language typescript
2. npx cdk synth
3. cp ./cdk.out/XxxStack.template.json ./template.txt
4. mkdir migrate
5. cd migrate
6. npx cdk migrate
then got this code (`lib/generated_stack.ts`)
```ts
import * as cdk from 'aws-cdk-lib';
import * as cdk from 'aws-cdk-lib/aws-cdk';
export interface NoctStackProps extends cdk.StackProps {
/**
* Version of the CDK Bootstrap resources in this environment, automatically retrieved from SSM Parameter Store. [cdk:skip]
* @default …
```
> feat: support non primitive parameters

- .gitignore
It looks like we'll actually need this generated file for publishing. If the file is ignored we get an error on publishing commands that there is an uncommited file.
> chore: add needed files for publishing

- .github/workflows/release-sync.yml
- .github/workflows/release.yml
- Cargo.toml
Fixes https://github.com/cdklabs/cdk-from-cfn/issues/222
This change adds the release-sync workflow, which once per day will push any changes to the `release` branch.
On a push to that branch, the release workflow will increment the version, publish the new version to crates.io, tag the release commit, and then push the commit back to the release branch. It then creates an auto-approve PR to push the release back to main.
Lastly, the wasm-pack is built from the `release` and released to npm.
> chore: add release workflows for crates and npm

- .github/workflows/release.yml
- build.rs
This is causing the release to fail because it generates node_modules and the cargo release command builds as part of the release. If fails upon detection of any changes not already committed.
This also contains a couple fixes to the release workflow.
Fixes #
> chore: remove yarn install from build

- .github/workflows/release.yml
Adding the --no-confirm flag so it works in ci/cd
Fixes #
> chore: make cargo release ci/cd friendly

- src/lib.rs
- src/synthesizer/typescript/mod.rs
The `no_coverage` attribute has been replaced with a new `coverage` attribute that takes `on` or `off` as a parameter - see this (PR)[https://github.com/rust-lang/rust/pull/114656]. This PR makes this update.
> chore: replace `no_coverage` attribute with new `coverage` attribute

- src/synthesizer/java/mod.rs
- tests/end-to-end.rs
- tests/end-to-end/simple/App.java
- tests/end-to-end/vpc/App.java
> fix(java): default imports do not match CDK init templates

- .github/workflows/security-audit.yml
- .github/workflows/status-checks.yml
This adds a check to each individual PR as well as a daily check. The checks on individual PRs will ensure we don't merge anything with changes that include bad dependencies. It will fail the workflow so it cannot be merged. The cron job will cut an issue on a failure, in the case of emergent security advisories for dependencies we're already using.
Fixes #
> chore: add security audits

- src/synthesizer/python/mod.rs
- tests/end-to-end/simple/app.py
- tests/end-to-end/vpc/app.py
Fixes the bug I was getting when deploying integ tests. Seems getatt was misformatting the attribute names
```
File "/private/var/folders/7z/jm3q4jws2mdcjw47_sswyw0m0000gr/T/cdk-integ-0mw87ejmm3pg/cdktest-0mw87ejmm3pg-python-migrate-stack/cdktest_0mw87ejmm3pg_python_migrate_stack/cdktest_0mw87ejmm3pg_python_migrate_stack_stack.py", line 48, in __init__
'value': myQueue.attrqueueName,
^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'CfnQueue' object has no attribute 'attrqueueName'. Did you mean: 'attr_queue_name'?
```
> chore: fix bug in python synth

- src/synthesizer/golang/mod.rs
- tests/end-to-end/simple/app.go
- tests/end-to-end/vpc/app.go
The generation of the SSM Parameter still isn't quite right but we have TODOs for that in here and I'm leaving it as a separate task. This is to enable implementation in the CDK CLI.
> feat(go): add app and env functions

- src/synthesizer/csharp/mod.rs
- tests/end-to-end/vpc/App.cs
Fixes 
```
/private/var/folders/7z/jm3q4jws2mdcjw47_sswyw0m0000gr/T/cdk-integ-0453ig8l6lrx/cdktest-0453ig8l6lrx-csharp-migrate-stack/src/Cdktest0453Ig8L6LrxCsharpMigrateStack/Cdktest0453Ig8L6LrxCsharpMigrateStackStack.cs(28,87): error CS0246: The type or namespace name 'Cdktest0453Ig8L6LrxCsharpMigrateStackStackProps' could not be found (are you missing a using directive or an assembly reference?) [/private/var/folders/7z/jm3q4jws2mdcjw47_sswyw0m0000gr/T/cdk-integ-0453ig8l6lrx/cdktest-0453ig8l6lrx-csharp-migrate-stack/src/Cdktest0453Ig8L6LrxCsharpMigrateStack/Cdktest0453Ig8L6LrxCsharpMigrateStack.csproj]
```
> chore: make csharp props create when empty

- src/ir/outputs/mod.rs
- tests/end-to-end/simple/template.yml
The way Noctilucent is handling exports is not correct. 
**Background**
Exports in CFN look like this:
```
Outputs:
BucketArn:
Condition: IsUsEast1
Description: The ARN of the bucket in this template!
Export:
Name: ExportName
```
NOT this:
```
Outputs:
BucketArn:
Condition: IsUsEast1
Description: The ARN of the bucket in this template!
Export: ExportName
```
**Bug**
If we give Noctilucent a template that looks like the first one today, it will produce incorrect CDK code:
```
new cdk.CfnOutput(this, 'BucketArn', {
description: 'The ARN of the bucket in this template!',
exportName: {
name: 'ExportName'
},
value: this.bucketArn,
});
```
It should just use `exportName: 'ExportName'` without the extra level of nesting for the name.
**Fix**
To fix this, we can either change all the synthesizers …
> fix: exports not handled correctly

- src/synthesizer/golang/mod.rs
- tests/end-to-end/simple/app.go
- tests/end-to-end/vpc/app.go
Fixes 
```
./cdktest-0jwrczbk9hlf-go-migrate-stack.go:46:9: undefined: awscdk
./cdktest-0jwrczbk9hlf-go-migrate-stack.go:48:81: cannot use &Cdktest0Jwrczbk9HlfGoMigrateStackStackProps{…} (value of type *Cdktest0Jwrczbk9HlfGoMigrateStackStackProps) as Cdktest0Jwrczbk9HlfGoMigrateStackStackProps value in argument to NewCdktest0Jwrczbk9HlfGoMigrateStackStack
./cdktest-0jwrczbk9hlf-go-migrate-stack.go:49:3: undefined: awscdk
./cdktest-0jwrczbk9hlf-go-migrate-stack.go:59:13: undefined: awscdk
```
> fix(go): wrong package name and referenced pointer instead of value

- src/main.rs
- src/synthesizer/csharp/mod.rs
- tests/end-to-end.rs
- tests/end-to-end/simple/App.cs
- tests/end-to-end/vpc/App.cs
The init'd CSharp app has a namespace conflict because the namespace in the generated app file is being created with the default namespace
```
namespace Com.Acme.Test.Simple
{
public class Cdktest01Z00Mg0HtbkCsharpMigrateStackStackProps : StackProps
{
}
/// <summary>
/// AWS CloudFormation Sample Template SQS_With_CloudWatch_Alarms: Sample template showing how to create an SQS queue with AWS CloudWatch alarms on queue depth.
/// </summary>
public class Cdktest01Z00Mg0HtbkCsharpMigrateStackStack : Stack
{
```
But the namespace of the program.cs file is using the stack name
```
namespace Cdktest01Z00Mg0HtbkCsharpMigrateStack
{
sealed class Program
{
public static void Main(string[] args)
{
var app = new App();
new Cdktest01Z00Mg0HtbkCsharpMigrateStackStack(app, …
```
> fix: CSharp uses a different namespace than init template

- src/synthesizer/python/mod.rs
- tests/end-to-end/simple/app.py
Fixes 
```
File "/Users/bobertzh/work/deleteme/temp/GoodPython/good_python/good_python_stack.py", line 30, in __init__
s3Bucket.cfnOptions.deletionPolicy = cdk.CfnDeletionPolicy.RETAIN
^^^^^^^^^^^^^^^^^^^
AttributeError: 'CfnBucket' object has no attribute 'cfnOptions'. Did you mean: 'cfn_options'?
```
> fix(python): resource attribute formatting uses camel case

- src/synthesizer/python/mod.rs
- tests/end-to-end/simple/app.py
Fixes #
Python joins were:
```
self.s3_bucket_secure_u_r_l = [
'https://',
s3Bucket.attr_domain_name,
].join('')
```
Which is not how python does joins. They are now:
```
''.join([
'https://',
s3Bucket.attr_domain_name,
])
```
which is how python does joins
> fix: incorrectly formatted python joins

- src/synthesizer/csharp/mod.rs
> fix(csharp): resource name is not cased correctly

- src/ir/constructor/mod.rs
- src/ir/constructor/tests.rs
- src/parser/parameters/mod.rs
- src/synthesizer/csharp/mod.rs
- src/synthesizer/java/mod.rs
- src/synthesizer/typescript/mod.rs
- tests/end-to-end/documentdb/template.yml
When "AllowedValues" in the CloudFormation template is populated and the allowed values are "true" and "false", the CDK translates these props into a boolean instead of a string. However, when other allowed values are present, the prop should still be represented as a string. 
As before, I have not included the tests, as before, because they're not fully passing yet but I've attached the template that I'm working against for reference. This template contains an example of allowed values that should resolve to a string, while the last template I uploaded translates allowed values that should resolve to a boolean.
Fixes https://github.com/cdklabs/cdk-from-cfn/issues/318
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the …
> fix(all): booleans are processed as strings causing failures

- src/synthesizer/java/mod.rs
This is bad and Java should feel bad. Java doesn't use DELETE as a RemovalPolicy value and uses DESTROY instead.
Fixes #
> fix(java): removal policy uses different enum values than other languages

- src/synthesizer/python/mod.rs
- tests/end-to-end/simple/app.py
Currently python outputs were being both emitted as a class variable at the bottom of the class and as a global variable at the top of the class. I chose to emit them as globals to make it obvious what their purpose was and to pretend python has some consistency with other languages which require you declare your class variables before assigning their values in the constructor. This was not a pythonic way of doing this so I'm removing it and instead I'm just annotating the pydoc descriptions to the class variables themselves. 
> fix(python): python outputs weren't very pythonic

- src/synthesizer/python/mod.rs
Previously python apps would fail lambda because we would be using the keyword lambda. i.e.
```
import aws_cdk.aws_lambda as lambda
lambdaFunction = lambda.CfnFunction(self, 'LambdaFunction'
```
fixed by only adding `aws_` before a lambda import
```
import aws_cdk.aws_lambda as aws_lambda
lambdaFunction = aws_lambda.CfnFunction(self, 'LambdaFunction'
```
Fixes # https://github.com/cdklabs/cdk-from-cfn/issues/319
> fix(python): python reserved keywords overlapping with service names

- src/synthesizer/python/mod.rs
- tests/end-to-end/simple/app.py
Fixes Python props not being properly retrieved from kwargs, as well as a couple spots where we were using camel case instead of snake case
> fix(python): props being improperly formatted

- src/synthesizer/typescript/mod.rs
- tests/end-to-end/config/app.ts
- tests/end-to-end/documentdb/app.ts
- tests/end-to-end/simple/app.ts
The type required in fields often does not allow for undefined. When a default value is provided we know the prop will not be undefined so we should assert that it is defined. Other props are required so we can just add the `!` across the board.
This also adds the TypeScript tests as they now synthesize with these changes (note that the props without default values required adding those values in, but we expect that."
> fix(typescript): props are potentially undefined when default value is provided

- src/synthesizer/python/mod.rs
- tests/end-to-end/simple/app.py
Fixes Exported values in python must be strings and nothing else. Casting exported value to string
> fix(python): boolean exported values must be strings

- src/synthesizer/python/mod.rs
- tests/end-to-end/simple/app.py
I realized I didn't need a ternary operator to default these values and that the second positional argument of kwargs.get is a built in default value
> fix(python): Python props were ugly and not very pythonic

- src/synthesizer/typescript/mod.rs
- tests/end-to-end/simple/app.ts
Fixes: exported value only expects a string but we would give it any type. Fixing this by casting it to a string
```
Type 'string | undefined' is not assignable to type 'string'.
Type 'undefined' is not assignable to type 'string'
```
> fix(typescript): exported type mismatch

- src/ir/importer/mod.rs
- src/synthesizer/csharp/mod.rs
- src/synthesizer/golang/mod.rs
- src/synthesizer/java/mod.rs
- src/synthesizer/python/mod.rs
- src/synthesizer/typescript/mod.rs
- tests/end-to-end/config/App.cs
- tests/end-to-end/config/App.java
- tests/end-to-end/documentdb/App.cs
- tests/end-to-end/documentdb/App.java
- tests/end-to-end/resource_w_json_type_properties/App.cs
- tests/end-to-end/resource_w_json_type_properties/App.java
- tests/end-to-end/simple/App.java
- tests/end-to-end/vpc/App.java
This required quite a bit of refactoring since the default case we were using was for typescript. We shouldn't be setting those defaults in IR so I removed it and handled the language specific logic in each language synthesizer.
This change legitimately fixes the issue for all use cases (or at least every one we have in the cdk library.
Fixes https://github.com/cdklabs/cdk-from-cfn/issues/214
> fix(csharp): import statements are incorrectly cased

- src/synthesizer/python/mod.rs
This change updates default values in boolean props to use Pascal Case.
Fixes #
> fix(python): booleans are not capitalized

- src/synthesizer/typescript/mod.rs
- tests/end-to-end/config/app.ts
- tests/end-to-end/documentdb/app.ts
- tests/end-to-end/simple/app.ts
Fixes 
originally if a customer had an output but not an export we just weren't creating a cfn output. This changes that so we are always putting out an output, but the optionally adding an export if it was an export
> fix(typescript): outputs only conditionally being created

- src/synthesizer/python/mod.rs
- src/synthesizer/typescript/mod.rs
- tests/end-to-end/config/app.py
- tests/end-to-end/config/app.ts
- tests/end-to-end/resource_w_json_type_properties/app.py
- tests/end-to-end/resource_w_json_type_properties/app.ts
Neither typescript nor json were differentiating between simple and comoplex resource structures so they were incorrectly camelcasing all of the keys of a json string. This change leaves the keys as is when they are a simple structure, i.e., plain json.
Fixes #https://github.com/aws/aws-cdk/issues/28014
> fix(typescript, python): iam policy keys are camel cased

- src/synthesizer/csharp/mod.rs
- src/synthesizer/golang/mod.rs
- src/synthesizer/java/mod.rs
- src/synthesizer/python/mod.rs
- src/synthesizer/typescript/mod.rs
- tests/end-to-end/config/App.java
- tests/end-to-end/config/app.py
- tests/end-to-end/config/app.ts
- tests/end-to-end/documentdb/App.java
- tests/end-to-end/documentdb/app.py
- tests/end-to-end/documentdb/app.ts
- tests/end-to-end/simple/App.cs
- tests/end-to-end/simple/App.java
- tests/end-to-end/simple/app.go
- tests/end-to-end/simple/app.py
- tests/end-to-end/simple/app.ts
This change adds the prefix 'CfnOutput' to each of the output construct IDs and then adds the key field to set the correct key.
Fixes https://github.com/cdklabs/cdk-from-cfn/issues/404
> fix(all): cfnOutput with the same key as construct causes collision in construct id

- src/synthesizer/csharp/mod.rs
- tests/end-to-end/config/App.cs
- tests/end-to-end/documentdb/App.cs
- tests/end-to-end/simple/App.cs
In this case, set props to default constructor.
> fix(csharp): if user does not supply props to stack constructor, they remain null and cause a C# runtime error

- src/synthesizer/golang/mod.rs
- tests/end-to-end/config/app.go
- tests/end-to-end/documentdb/app.go
- tests/end-to-end/resource_w_json_type_properties/app.go
- tests/end-to-end/simple/app.go
- tests/end-to-end/vpc/app.go
This fixes 3 issues in order to allow the most basic of go stacks to work. It does not fix all current issues with go, so the title might be a bit too broad. If anyone has suggestions for a better title here, I'd love to here it.
| | Issue  | Fix |
|-| ------------- | ------------- |
|1| A file produced by cdk-from-cfn cannot be used as the main executable in a CDK app because it declares a `main` function in a package that is not called main.  | change the package name line to `package main`. See https://go.dev/doc/modules/layout |
|2| The props parameter of the Stack constructor is not a pointer, which prevents it from being able to be optional. | Make props a pointer.  |
|3| If `nil` is supplied as the prop argument of the Stack constructor, a runtime error occurs because we cannot …
> fix(go): cdk-from-cfn does not produce working go files

- src/synthesizer/csharp/mod.rs
- tests/end-to-end/config/App.cs
- tests/end-to-end/documentdb/App.cs
This was unintentionally hard-coded in a previous change to the name of the stack props in one of the end-to-end test cases.
> fix(csharp): setting default prop value uses incorrect props class name

- src/synthesizer/typescript/mod.rs
- tests/end-to-end/config/app.ts
- tests/end-to-end/documentdb/app.ts
- tests/end-to-end/resource_w_json_type_properties/app.ts
- tests/end-to-end/simple/app.ts
- tests/end-to-end/vpc/app.ts
These are of no use to the end user and just add noise to the template.
Note that with this change, the integ tests in aws-cdk will likely need to be updated manually.
Fixes #
> chore(typescript): remove troubleshooting lines

- src/ir/importer/mod.rs
- src/ir/resources/mod.rs
- src/lib.rs
- src/synthesizer/csharp/mod.rs
- src/synthesizer/golang/mod.rs
- src/synthesizer/java/mod.rs
- src/synthesizer/python/mod.rs
- src/synthesizer/typescript/mod.rs
- tests/end-to-end.rs
- tests/end-to-end/sam_nodejs_lambda/App.cs
- tests/end-to-end/sam_nodejs_lambda/App.java
- tests/end-to-end/sam_nodejs_lambda/app.go
- tests/end-to-end/sam_nodejs_lambda/app.py
- tests/end-to-end/sam_nodejs_lambda/app.ts
- tests/end-to-end/sam_nodejs_lambda/template.yml
- tests/end-to-end/sam_nodejs_lambda_arr_transform/App.cs
- tests/end-to-end/sam_nodejs_lambda_arr_transform/App.java
- tests/end-to-end/sam_nodejs_lambda_arr_transform/app.go
- tests/end-to-end/sam_nodejs_lambda_arr_transform/app.py
- tests/end-to-end/sam_nodejs_lambda_arr_transform/app.ts
- tests/end-to-end/sam_nodejs_lambda_arr_transform/template.yml
In aws-cdk, we renamed Serverless to SAM so we need to do that here as well. This change also adds the transform field, reading from both a string value and an array.
Fixes https://github.com/cdklabs/cdk-from-cfn/issues/366
Fixes https://github.com/cdklabs/cdk-from-cfn/issues/365
> fix(all): serverless does not resolve correctly

- docs/1_overview.md
AmiId is hard to read. `AmiId` is easier.
> docs: readability nit

- docs/2_conditions.md
Looks like some of the variable names are different from the code snippets and the bullet point explanations. This fixes some of them.
Are these intentional? I cannot see a reason why they would be, but it is possible.
Also, we have some inconsistency between '==' and '===' for `Fn::Equals`, is there a standard, or do we use both in different cases?
> docs: align variable names

- .github/workflows/status-checks.yml
- tests/end-to-end/app-boilerplate-files/java/pom.xml
- tests/end-to-end/app-boilerplate-files/java/setup-and-synth.sh
The pom.xml file we are using here is for Java 8 but the cdk uses Java 17.
Fixes #
> test(java): update boilerplate pom.xml to use the same versions as aws-cdk

- src/lib.rs
The npm release is failing due to the settings for CSharp not being updated in the wasm_bindgen configuation. This fixes that.
Fixes #
> fix(release): npm release is not using CSharp default

- src/ir/constructor/mod.rs
- src/ir/constructor/tests.rs
- src/ir/mod.rs
- src/ir/reference/mod.rs
- src/ir/resources/mod.rs
- src/parser/parameters/mod.rs
- src/synthesizer/csharp/mod.rs
- src/synthesizer/golang/mod.rs
- src/synthesizer/java/mod.rs
- src/synthesizer/python/mod.rs
- src/synthesizer/typescript/mod.rs
- tests/end-to-end/documentdb/csharp/Stack.cs
- tests/end-to-end/documentdb/csharp/Stack.diff
- tests/end-to-end/documentdb/csharp/Stack.template.json
- tests/end-to-end/documentdb/java/Stack.diff
- tests/end-to-end/documentdb/java/Stack.template.json
- tests/end-to-end/documentdb/java/src/main/java/com/myorg/Stack.java
- tests/end-to-end/documentdb/python/Stack.diff
- tests/end-to-end/documentdb/python/Stack.template.json
- tests/end-to-end/documentdb/python/stack.py
- tests/end-to-end/documentdb/typescript/Stack.diff
- tests/end-to-end/documentdb/typescript/Stack.template.json
- tests/end-to-end/documentdb/typescript/stack.ts
- tests/tests.rs
If a user supplies a template that contains parameters wiht noEcho set to true, we are currently not translating that in a way that prevents it from showing in the stack. This adds handling to make parameters wtih noEcho into CfnParameters with the same set.
Fixes #
> fix(all): noEcho parameters still show in deployed template

- src/synthesizer/java/mod.rs
I am seeing [workflows](https://github.com/cdklabs/cdk-from-cfn/actions/runs/7844052695/job/21405613049?pr=558) fail for this repo due to clippy error:
```
error: writing `&Vec` instead of `&[_]` involves a new object where a slice will do
Error:    --> src/synthesizer/java/mod.rs:123:16
|
123 |         props: &Vec<JavaConstructorParameter>,
|                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: change this to: `&[JavaConstructorParameter]`
|
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#ptr_arg
= note: `-D clippy::ptr-arg` implied by `-D warnings`
= help: to override `-D warnings` add `#[allow(clippy::ptr_arg)]`
error: could not compile `cdk-from-cfn` (lib) due to 1 previous error
Error: The process '/home/runner/.cargo/bin/cargo' failed …
```
> chore: address clippy recommendations

- README.md
The `README` user guide section contains the following instructions:
```
$ cargo build --release
$ ./target/release/cdk_from_cfn [INPUT] [OUTPUT]
```
However, after running `cargo build --release` the following `target` directory is created:
As shown, the `target` directory contains a `release` directory with `cdk-from-cfn`, not `cdk_from_cfn`.
> chore: update readme user guide to use correct release binary file name

- src/ir/resources/mod.rs
- tests/tests.rs
In the event that an invalid property is specified for a specific resource type the `value_type` will be `None` causing the `other` arm of the match statement below to execute.
https://github.com/cdklabs/cdk-from-cfn/blob/2c14390f73b765b961a71b0cc2952fe87af587fb/src/ir/resources/mod.rs#L119-L129
Due to the `unimplemented!` macro panicking in-place, a non-descriptive error message is displayed while using cdk migrate:
```
cdk migrate --from-path './CDKMigrateExampleTemplate.yml' --stack-name CustomStackName
...
❌  Migrate failed for `CustomStackName`: stack generation failed due to error 'unreachable'
stack generation failed due to error 'unreachable'
```
This PR adds a new explicit check for the case where `property_type` is `None`. If that case is true, then a more descriptive error …
> chore(ir): add specific error message when an invalid resource property is used

- src/ir/constructor/mod.rs
- src/ir/mappings/mod.rs
- src/ir/mod.rs
This PR adds the ability to be able print the `CloudformationProgramIr`. This is helpful while implementing new features and while fixing bugs because we're able to see the `CloudformationProgramIr` structure and data types while developing.
> chore: derive debug for `CloudformationProgramIr`

- src/ir/constructor/mod.rs
- tests/end-to-end/groundstation/template.json
We are checking for the second value of allowed values first when checking for booleans. This causes a failure when only one allowed value is provided for a parameter.
This PR includes the template that is being tested against but not the test cases because there are still other failures. The next PR will include the test cases and a fix for the bug preventing a successful run.
Fixes part of https://github.com/aws/aws-cdk/issues/29752
> fix(all): a single allowed value causes failure

- Cargo.lock
- Cargo.toml
The version of rust we're using is no longer compatible with some of our tooling so this upgrades rust and then upgrades a whole bunch of other dependencies based off the security alerts created from that initial upgrade.
> chore: update rust version

- Cargo.lock
- src/ir/sub/mod.rs
- src/lib.rs
- src/parser/resource/mod.rs
- src/synthesizer/java/mod.rs
- tests/end-to-end/app-boilerplate-files/csharp/CSharp.csproj
Fixes clippy lint breaking
Removed some unused code, along with small safe fixes from clippy. Clippy continuously updates what it sees as redundant or not Rust idiomatic, and 1.80 added a few more to the list that are safe.
> chore: appease clippy violations

- .github/workflows/status-checks.yml
Required to for the security audit action to update status checks from merge group.
Permissions as documented: https://github.com/rustsec/audit-check?tab=readme-ov-file#granular-permissions
---
> chore: add checks permissions for security_audit

- .github/workflows/status-checks.yml
The previous attempt was lacking the config file, because the repo wasn't checked out in the upload step.
Fix this but also simplify the setup.
> chore: fix codecov report not using config 

- src/ir/resources/mod.rs
- src/ir/resources/tests.rs
- tests/end-to-end/cloudwatch/csharp/Stack.cs
- tests/end-to-end/cloudwatch/csharp/Stack.diff
- tests/end-to-end/cloudwatch/csharp/Stack.template.json
- tests/end-to-end/cloudwatch/golang/stack.go
- tests/end-to-end/cloudwatch/java/Stack.diff
- tests/end-to-end/cloudwatch/java/Stack.template.json
- tests/end-to-end/cloudwatch/java/src/main/java/com/myorg/Stack.java
- tests/end-to-end/cloudwatch/python/Stack.diff
- tests/end-to-end/cloudwatch/python/Stack.template.json
- tests/end-to-end/cloudwatch/python/stack.py
- tests/end-to-end/cloudwatch/template.json
- tests/end-to-end/cloudwatch/typescript/Stack.diff
- tests/end-to-end/cloudwatch/typescript/Stack.template.json
- tests/end-to-end/cloudwatch/typescript/stack.ts
There were certain templates that errored out and said "not a valid integer". When looking at the code, it turns out that if a string thinks there is a number -- a number in JSON can be either integer or doable. Originally, the code parsed only ints, so any float/double fails outright. This update now will try both. I'm sure in the future we will need to try to parse one, fail, parse the other -- but for now, just look for a ".".
Fixes #750
> fix: allow translation of doubles from strings

- Cargo.lock
> chore: bump a number of dependencies to get rid of security warnings

- .github/workflows/release-sync.yml
The `Daily Release Check` workflow is failing with:
```console
Run baptiste0928/cargo-install@v3
Installing cargo-release...
Fetching information for cargo-release from index ...
Warning: New version for cargo-release available: 0.25.[15](https://github.com/cdklabs/cdk-from-cfn/actions/runs/12642594859/job/35230670983#step:5:16)
Installation settings:
version: 0.25.13
path: /home/runner/.cargo-install/cargo-release
key: cargo-install-cargo-release-0.25.13-f2b21f4ec7854a6977ea1ffc
command: cargo install cargo-release --force --root /home/runner/.cargo-install/cargo-release --version 0.25.13 --locked
No cached version found, installing cargo-release using cargo...
/home/runner/.cargo/bin/cargo install cargo-release --force --root /home/runner/.cargo-install/cargo-release --version 0.25.13 …
```
> chore: current version of `cargo-release` is not installable

- .github/workflows/status-checks.yml
Previously blocked due to bugs in the latest major version. They should now be fixed.
> chore: update codecov-action to v5

- .github/workflows/status-checks.yml
Prevents codecov from blocking CI, until they fix the following:
https://github.com/codecov/codecov-action/issues/1806
https://github.com/codecov/codecov-action/pull/1792
> fix: prevent codecov upload failure from blocking CI

- .github/workflows/status-checks.yml
Resolution of https://github.com/codecov/codecov-action/issues/1806 prevents codecov uploads from breaking now.
Fixes #908 
> fix: re-enable blocking changes that fail codecov

- .github/workflows/update-rust-version.yml
- Cargo.toml
This PR removes the rust-version field from Cargo.toml and adds an automated workflow to keep the Rust toolchain up to date.
- Remove rust-version field from Cargo.toml to avoid version conflicts with rust-toolchain.toml
- Add GitHub workflow that automatically updates rust-toolchain.toml with the latest stable Rust version
- Workflow runs weekly on Mondays and can be triggered manually
The rust-version field in Cargo.toml can conflict with the version specified in rust-toolchain.toml. By removing it and relying on the automated workflow, we ensure consistent Rust version management and stay up to date with the latest stable releases.
> chore: remove rust-version field and add automated rust update workflow
