cdklabs/cdk-from-cfn

docs/3_lookups.md, src/lib.rs, src/main.rs, src/parser/lookup_table.rs, src/parser/mod.rs
First draft of parser/synthesizer of CloudFormation Mappings from JSON -> Typescript
=> Add parser/synthesizer for CloudFormation mappings

Cargo.toml, src/main.rs, src/parser/condition.rs, src/parser/lookup_table.rs, src/semantic/importer.rs, src/semantic/mod.rs
First bit for all resource output, imports, and fix mappings in
the output.
=> Add full builder

src/main.rs
Tests performed: `cargo build --release; cargo run`
=> fix: Changed Arg::about to Arg::help

src/synthesizer/typescript_synthesizer.rs
Turns out it doesn't work. Fixes #67
=> Fix getAZ translation

src/parser/condition.rs, src/parser/resource.rs, tests/tests.rs
Addresses #96 for not supporting the YAML shorthand forms.
=> Add support for YAML shorthand

src/main.rs
=> fix: remove inputFormat CLI option

tests/tests.rs
added test for https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/intrinsic-function-reference-findinmap.html
=> chore: add test for fn:FindInMap

CONTRIBUTING.md
Straightforward change, like the title suggests.
=> chore: Adding a contributing guide

tests/tests.rs
added a simple unit test for fn::join
=> chore: add unit test for fn::join

Cargo.toml, src/ir/constructor.rs, src/parser/output.rs, src/parser/parameters.rs, src/synthesizer/typescript_synthesizer.rs, tasks/coverage.sh, tests/end-to-end.rs, tests/end-to-end/simple/app.ts, tests/end-to-end/simple/template.yml
Adding an end-to-end test suite to validate proper output of TypeScript code today, before refactoring the output API.
=> chore: add output unit tests + some style fixes

src/ir/conditions.rs, src/ir/constructor.rs, src/ir/importer.rs, src/ir/mappings.rs, src/ir/mod.rs, src/ir/outputs.rs, src/ir/reference.rs, src/ir/resources.rs, src/lib.rs, src/main.rs, src/parser/resource.rs, src/primitives/mod.rs, src/specification/mod.rs, src/synthesizer/typescript_synthesizer.rs, tasks/coverage.sh, tests/end-to-end.rs, tests/end-to-end/simple/app.ts, tests/end-to-end/simple/template.yml, tests/end-to-end/vpc/app.ts, tests/end-to-end/vpc/template.yml, tests/tests.rs
Also add support for template description to be forwarded in the generated code as the stack's documentation comments.
=> depend: further enhance test coverage

src/ir/constructor.rs, src/parser/parameters.rs
=> chore: Added unit tests

Cargo.lock, Cargo.toml, src/lib.rs, src/main.rs
- dependencies for wasmification
- wasm lib function
=> chore: add wasm target option

.github/workflows/release.yml
=> chore: add a wasm-pack build to the release

.gitignore, Cargo.toml, README.md, src/main.rs, src/synthesizer/java/mod.rs, src/synthesizer/mod.rs, tests/end-to-end.rs, tests/end-to-end/simple/App.java, tests/end-to-end/vpc/App.java
Documented the edge-case of typed resource properties in `CDK Migrate - Burndown`.
=> feat: Java support

src/synthesizer/java/mod.rs, tests/end-to-end/simple/App.java
Java was missing Metadata, DeletionPolicy, UpdatePolicy, and DependsOn. This PR adds those.
=> feat(java): add resource attributes

CONTRIBUTING.md, Cargo.lock, Cargo.toml, README.md, docs/1_overview.md, docs/2_conditions.md, docs/3_lookups.md, src/ir/README.md, src/main.rs, src/parser/README.md, src/specification/mod.rs, src/synthesizer/README.md, tests/end-to-end.rs, tests/end-to-end/go.mod, tests/tests.rs
This change also includes automatic formatting changes done by my linter and properly sets up the exclusion of test files for publishing
=> chore: change name in all locations where noctilucent is present

.github/workflows/update-schema.yml
No path is needed and git diff should come after the build
Fixes #
=> chore: fix update-schema workflow

.github/workflows/release.yml
=> chore: set git credentials before release

src/lib.rs
=> feat: enable all languages in wasm distribution

Cargo.lock, Cargo.toml
=> chore: Release cdk-from-cfn version 0.8.0

.github/workflows/release.yml, Cargo.lock, Cargo.toml
=> chore: Release cdk-from-cfn version 0.9.0

src/lib.rs
=> fix: lib still uses default for csharp

.github/workflows/release.yml
=> chore: trying again to improve release flow

.github/workflows/release.yml
=> chore: add credentials to checkout

.github/workflows/release.yml
=> chore: update wasm-pack to use release branch

.github/workflows/release.yml
=> chore: use the newly created branch to determine the npm version

src/synthesizer/csharp/mod.rs, tests/end-to-end/config/App.cs, tests/end-to-end/documentdb/App.cs
The bool must be nullable. Thanks for the assist @madeline-k!
Now that the tests will pass and the code synths, I've added the C# ones in this PR.
Fixes #
=> fix(csharp): bool cannot use ??=

tests/end-to-end/config/App.java, tests/end-to-end/documentdb/App.java
=> chore(java): add in the tests we've been testing against

tests/end-to-end/config/app.go, tests/end-to-end/documentdb/app.go
These don't synth. We know they're still broken.
Fixes #
=> chore(go): add test results

src/synthesizer/python/mod.rs, tests/end-to-end/simple/app.py
It should be snake cased.
Fixes #
=> fix(python): addDependency is camelcased

src/synthesizer/python/mod.rs, tests/end-to-end/simple/app.py, tests/end-to-end/vpc/app.py
Fixes improper naming scheme for properties
=> fix(python): camel case where there should be snake case

src/synthesizer/python/mod.rs, tests/end-to-end/config/app.py, tests/end-to-end/documentdb/app.py
The function pretty_name is not handling the casing correctly. This change uses the snake_case function to correct this.
This also includes the test cases I've been checking against with all the python changes. With this last change, they now synth!
After my three changes get merged, I will add the code that actually runs these new tests.
Fixes #
=> fix(python): pretty_name is not snake_case

tests/end-to-end.rs
These are the tests that I have been running manually in my workspace to check all the various fixes. This change actually makes them run.
Note that they will not pass until all three of the last PRs have been merged. This is expected.
Fixes #
=> chore: turn on tests for more test cases

src/synthesizer/python/mod.rs, tests/end-to-end/simple/app.py
=> fix(python): default values for parameters cause python runtime error

src/synthesizer/python/mod.rs, tests/end-to-end/simple/app.py
- minor comment update
- fix multiline bug with sub parts
Fixes #455 
=> fix(python): python synthesizer improperly handling f strings in resource props

build.rs, tests/end-to-end.rs
Our release workflow is failing due to the addition of the zip file created for the tests. This change moves it to a temp folder.
=> fix(tests): zip file causes failure in cargo release

src/synthesizer/csharp/mod.rs, tests/end-to-end.rs, tests/end-to-end/sam_nodejs_lambda/csharp/Program.cs, tests/end-to-end/sam_nodejs_lambda/csharp/Stack.cs, tests/end-to-end/sam_nodejs_lambda/csharp/Stack.diff, tests/end-to-end/sam_nodejs_lambda/csharp/Stack.template.json, tests/end-to-end/sam_nodejs_lambda_arr_transform/csharp/Stack.cs
=> fix(csharp): multi-line string does not render

tests/end-to-end.rs, tests/end-to-end/sam_nodejs_lambda/golang/Stack.diff, tests/end-to-end/sam_nodejs_lambda/golang/Stack.template.json, tests/end-to-end/sam_nodejs_lambda/golang/app.go
=> tests(go): some tests work

src/lib.rs
=> fix: missing import statement

CONTRIBUTING.md, README.md
Adding some documentation updates while learning more about this repository.
=> chore: documentation updates

src/specification/cdk-resources.json
=> chore: update schema

.github/workflows/security-audit.yml, .github/workflows/status-checks.yml
To fix the failing action. `main` branch doesn't exist.
=> chore: update security-audit.yml

.github/workflows/status-checks.yml
=> chore: renable codecov

.github/workflows/release-sync.yml
=> chore: fix cargo-release to a specific version

ARCHITECTURE.MD, CONTRIBUTING.md, README.md, src/synthesizer/README.md
Updating the markdown documentation to better describe the architecture of the project and how to use it
=> docs: update existing markdown documentation and add architecture overview
